# https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71

version: '3'
services:

  # REVERSE PROXY
  nginx:
    image: nginx:1.15-alpine
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - certbot
      - docker-registry
      - wikijs
      # - cryptpad
    volumes:
      - ./services/nginx:/etc/nginx/conf.d
      - ~/storage/certbot/conf:/etc/letsencrypt # we need rw to run openssl
      - ~/storage/certbot/www:/var/www/certbot:ro
      - ./services/www:/var/www/html # placeholder HTML web site
    networks:
      - proxy-network

  # LETSENCRYPT MANAGER
  certbot:
    image: certbot/certbot
    container_name: certbot
    restart: always
    volumes:
      - ~/storage/certbot/conf:/etc/letsencrypt
      - ~/storage/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  # DOCKER REGISTRY
  docker-registry:
    image: registry:2
    container_name: docker-registry
    expose:
      - "5000" # allow the host to pull from localhost:5000
    ports:
      - "5000:5000"
    environment:
      - REGISTRY_STORAGE_DELETE_ENABLED=true
    volumes:
      - ~/storage/docker-registry:/var/lib/registry
    networks:
      - proxy-network
      
  # WIKI DB
  wikidb:
    image: mongo:3
    container_name: wikidb
    expose:
      - '27017'
    command: '--smallfiles --bind_ip ::,0.0.0.0'
    restart: always
    environment:
      - 'MONGO_LOG_DIR=/dev/null'
    volumes:
      - ~/storage/wikidb:/services/db
    networks:
      - databases-network
      
  # WIKI ENGINE
  wikijs:
    image: 'requarks/wiki:latest'
    container_name: wikijs
    restart: always
    depends_on:
      - wikidb
    expose:
      - '3000'
    environment:
      WIKI_ADMIN_EMAIL: wiki-admin@domain.com
    volumes:
      - ./services/wikijs/config.yml:/var/wiki/config.yml
    networks:
      - proxy-network
      - databases-network

  # ZK DRIVE
  cryptpad:
    container_name: wikijs
    image: "xwiki/cryptpad"
    hostname: cryptpad
    environment:
      - USE_SSL=false
      - STORAGE='./storage/file'
      - LOG_TO_STDOUT=true
    networks:
      - proxy-network
    restart: always
    volumes:
      - ~/storage/cryptpad/files:/cryptpad/datastore:rw
      - ~/storage/cryptpad/customize:/cryptpad/customize:rw
      - ~/storage/cryptpad/pins:/cryptpad/pins:rw
      - ~/storage/cryptpad/blob:/cryptpad/blob:rw
      - ~/storage/cryptpad/blobstage:/cryptpad/blobstage:rw
      - ~/storage/cryptpad/tasks:/cryptpad/tasks:rw
      - ~/storage/cryptpad/block:/cryptpad/block:rw

networks:
  proxy-network:
  databases-network:
