#!/bin/bash
PATH=./node_modules/.bin:$PATH
DOCKERFILE=docker-compose.yml

###############################################################################
# SERVER ACTIONS

function init {
  ./init-letsencrypt.sh
}

function logs {
  docker-compose -f $DOCKERFILE logs -f $1
}

function ps {
  docker ps | grep dockersuit
}

function build {
  docker-compose -f $DOCKERFILE build $1
}

function upgrade {
  build $1

  # will recreate newer container for updated images
  docker-compose -f $DOCKERFILE up -d
}

function restart {
  docker-compose -f $DOCKERFILE restart $1
}

function tidy_up {
  docker image prune
}

###############################################################################
# DEVELOPER ACTIONS


###############################################################################
# HELPERS


###############################################################################
# DEFAULT => INFO

function default {
  echo "$0 <task> <args>"
  echo
  echo "Available tasks:"
  compgen -A function | cat -n
}


TIMEFORMAT="Task completed in %3lR"
time ${@:-default}